import React from "react";
import * as AiIcons from "react-icons/ai";
import * as IoIcons from "react-icons/io";
import * as RiIcons from "react-icons/ri";
import * as FaIcons from "react-icons/fa";
import * as GrIcons from "react-icons/gr";

export const sidebarData = [
  {
    title: "Bảng điều khiển",
    path: "/Bang-dieu-khien",
    icon: <AiIcons.AiFillHome />,
  },
  {
    title: "Tiếp đón khám chữa bệnh",
    path: "/tiep-don-kham-chua-benh",
    icon: <FaIcons.FaBookMedical />,
    iconClosed: <RiIcons.RiArrowDownSFill />,
    iconOpened: <RiIcons.RiArrowUpSFill />,
  },
  {
    title: "Thu chi",
    path: "/thu-chi",
    icon: <IoIcons.IoIosPaper />,
    iconClosed: <RiIcons.RiArrowDownSFill />,
    iconOpened: <RiIcons.RiArrowUpSFill />,
    subNav: [
      {
        title: "Phiếu thu",
        path: "/thu-chi/phieu-thu",
        icon: <IoIcons.IoIosPaper />,
      },
      {
        title: "Phiếu chi",
        path: "/thu-chi/phieu-chi",
        icon: <IoIcons.IoIosPaper />,
      },
    ],
  },
  {
    title: "Khám bệnh",
    path: "/kham-benh",
    icon: <IoIcons.IoIosPaper />,
  },
  {
    title: "Cận lâm sàng",
    path: "/can-lam-sang",
    icon: <IoIcons.IoIosPaper />,
  },
  {
    title: "Xuất - bán thuốc",
    path: "/xuat-ban-thuoc",
    icon: <IoIcons.IoIosPaper />,
  },
  {
    title: "Bệnh nhân",
    path: "/benh-nhan",
    icon: <IoIcons.IoIosPaper />,
  },
  {
    title: "Quản lý kho",
    path: "/quan-ly-kho",
    icon: <IoIcons.IoIosPaper />,
    iconClosed: <RiIcons.RiArrowDownSFill />,
    iconOpened: <RiIcons.RiArrowUpSFill />,
  },
  {
    title: "Hệ thống",
    path: "/he-thong",
    icon: <IoIcons.IoIosPaper />,
    iconClosed: <RiIcons.RiArrowDownSFill />,
    iconOpened: <RiIcons.RiArrowUpSFill />,
    subNav: [
      {
        title: "Danh mục thông tin",
        path: "/he-thong/danh-muc-thong-tin",
        icon: <IoIcons.IoIosPaper />,
        iconClosed: <RiIcons.RiArrowDownSFill />,
        iconOpened: <RiIcons.RiArrowUpSFill />,
        subNavs: [
          {
            title: "Cơ sở khám chữa bệnh",
            path: "/he-thong/danh-muc-thong-tin/co-so-kham-chua-benh",
            icon: <IoIcons.IoIosPaper />,
            cName: "sub-nav",
          },
          {
            title: "Khoa - Phòng điều trị",
            path: "/he-thong/danh-muc-thong-tin/co-so-kham-chua-benh",
            icon: <IoIcons.IoIosPaper />,
            cName: "sub-nav",
          },
          {
            title: "Sản phẩm",
            path: "/he-thong/danh-muc-thong-tin/co-so-kham-chua-benh",
            icon: <IoIcons.IoIosPaper />,
            cName: "sub-nav",
          },
          {
            title: "Lịch làm việc",
            path: "/he-thong/danh-muc-thong-tin/co-so-kham-chua-benh",
            icon: <IoIcons.IoIosPaper />,
            cName: "sub-nav",
          },
        ],
      },
      {
        title: "Quản lý nhân sự",
        path: "/he-thong/quan-ly-nhan-su",
        icon: <IoIcons.IoIosPaper />,
      },
    ],
  },
];

export const rowstable = [
  {
    id: 1,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "2520 000 đ",
  },
  {
    id: 2,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "2120 000 đ",
  },
  {
    id: 3,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "220 000 đ",
  },
  {
    id: 4,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "220 000 đ",
  },
  {
    id: 5,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "1220 000 đ",
  },
  {
    id: 6,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "2220 000 đ",
  },
  {
    id: 7,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "220 000 đ",
  },
  {
    id: 8,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "2240 000 đ",
  },
  {
    id: 9,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "5220 000 đ",
  },
  {
    id: 10,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "220 000 đ",
  },
  {
    id: 11,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "220 000 đ",
  },
];

export const rowstable2 = [
  {
    id: 1,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "2520 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 2,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "2120 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 3,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 4,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 5,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "1220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 6,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "2220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 7,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 8,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "2240 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 9,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "5220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 10,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nữ",
    total: "220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
  {
    id: 11,
    date: "9-40 ngày 12/08/2021",
    username: "Cao Việt Bách",
    birthday: "31/12/2000",
    gender: "Nam",
    total: "220 000 đ",
    collector: "Nguyễn Văn Đức",
  },
];
